//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGHCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducation
    {
        public System.Guid CompanyId { get; set; }
        public int EducationId { get; set; }
        public string CourseName { get; set; }
        public string Institutions { get; set; }
        public int Experience { get; set; }
        public string Comments { get; set; }
        public decimal Percentages { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDated { get; set; }
        public byte[] RowVersion { get; set; }
        public string Document { get; set; }
        public int EmployeeId { get; set; }
    }
}
