//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGHCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDetail()
        {
            this.Resignations = new HashSet<Resignation>();
        }
    
        public System.Guid CompanyId { get; set; }
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string Designation { get; set; }
        public string EmailId { get; set; }
        public string EmployeeAddress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public int Gender { get; set; }
        public string PhoneNo { get; set; }
        public string AccountNo { get; set; }
        public string MaritalStatus { get; set; }
        public string EmployeeShift { get; set; }
        public string Nationality { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public byte[] RowVersion { get; set; }
        public string LastName { get; set; }
        public string Profile { get; set; }
        public string EmployeeCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resignation> Resignations { get; set; }
    }
}
